# Generated by Django 2.2.6 on 2019-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='summary',
            field=models.TextField(default='this is cool!'),
        ),
    ]
