# Generated by Django 2.2.6 on 2019-12-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_latestnews_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestNews',
            new_name='Latest',
        ),
    ]
