# Generated by Django 2.2.6 on 2019-12-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20191208_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latest',
            old_name='summary',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='latest',
            name='blog_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='latest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
