# Generated by Django 2.2.6 on 2019-12-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20191208_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latest',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image',
            field=models.TextField(),
        ),
    ]
